# Generated by Django 5.0.6 on 2024-06-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_customuser_username_alter_customuser_email'),
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
                ('complition_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receivers.receiver')),
            ],
        ),
    ]
